require: rubocop-rails

Layout/LineLength:
  Max: 250
  Exclude:
    - 'Gemfile'
AllCops:
  NewCops: enable

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'db/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/**/*'

Metrics/ClassLength:
  Max: 150

Rails/NotNullColumn:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false
  Exclude:
    - 'test/**/*'
    - 'db/**/*'

Style/GuardClause:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
