version: "3.9"
services:
  db:
    image: postgis/postgis:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_PASSWORD: password
      DATABASE_USER: postgres
      DATABASE_HOST: db
    volumes:
      - .:/myapp
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - web