default: &default
  adapter: postgis
  encoding: utf8
  username: <%= ENV['DATABASE_USER']%>
  password: <%= ENV['DATABASE_PASSWORD']%>
  host: <%= ENV['DATABASE_URL']%>
  pool: 5 # not mandatory
  timeout: 5000 # not mandatory
  port: 5432

test:
  <<: *default
  database: dockerized-rails_test
development:
  <<: *default
  database: dockerized-rails_development
production:
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis")%>